### ISSUE TITLE
Rails 3.2 is out

### ISSUE THREAD

**Issue by krainboltgreene** [dondurrance/tracker#4]
You're specifiying an old version of rails (`3.0.1.rc2`) and an RC at that. Up it to 3.2, follow some upgrade blogs instructions, and take advantage of that sweet pipeline.

**Comment by dondurrance** [comment]
Thank you SO much for your help! I'm creating a new app / repo for the 3.2 version with Sorcery just to make sure we don't have any randomness lying around from the old version. I'll send it to you when I'm done! :)

**Comment by krainboltgreene** [comment]
A better bet would be to create a new branch based on master, delete everything, commit the deletions, then build a new rails app inside with 3.2

That way later you can merge into master and visibly see the changes.
